# This file contains high level configuration parameters for setup 

# Parameters for the Ubuntu distribution
dist:
  name: focal
  vers: 20.04
# Parameters for destination media
device:
  name: /dev/sda
  pool: /mnt/btrfs_pool
  optn: ssd,noatime,compress=zstd,commit=120
  luks: crypt_root
# Parameters for chroot environment
droot:
  path: /mnt/debootpath
  user: mistborn
  host: scadrial
  tzne: America/Los_Angeles
  # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-consistent_network_device_naming
  # https://ubuntu.com/blog/ubuntu-bionic-netplan
  ndev: eno1
  addr: 172.26.75.103