# This file contains high level configuration parameters for setup 

# Parameters for the Ubuntu distribution
dist:
  name: focal
  vers: 20.04
# Parameters for destination media
device:
  name: /dev/sda
  pool: /mnt/btrfs_pool
  optn: ssd,noatime,compress=zstd,commit=120
  luks: crypt_root
# Parameters for chroot environment
droot:
  path: /mnt/debootpath
  user: mistborn
  host: scadrial
  tzne: America/Los_Angeles
# Parameters for netplan configuration
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-consistent_network_device_naming
# https://ubuntu.com/blog/ubuntu-bionic-netplan
network:
  # wide-area network
  wan:
    iface: eno1
    dhcp4: yes
    dhcp6: no
    gate4: 172.26.75.1
    haddr: 172.26.75.12
  # local-area network
  lan:
    iface: enp4s0
    addrs: 10.16.35.1/24
  # wireless network
  wap:
    iface: wlp2s0
    addrs: 10.16.45.1/24