# This file contains high level configuration parameters for setup 

# Parameters for destination media
media:
  device: /dev/sda
  pool: /mnt/btrfs_pool
  optn: ssd,noatime,compress=zstd,commit=120
  luks: crypt_root

# Parameters for chroot environment
droot:
  host: scadrial
  addr: 172.26.75.103
  # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-consistent_network_device_naming
  # https://ubuntu.com/blog/ubuntu-bionic-netplan
  ndev: eno1
  user: mistborn
  path: /mnt/debootpath
  dist: focal
  time: America/Los_Angeles
