# This file contains high level configuration parameters for setup 

scadrial:
  # Parameters for the Ubuntu distribution
  dist:
    name: focal
    vers: 20.04
  # Parameters for destination media
  device:
    name: /dev/sda
    pool: /mnt/btrfs_pool
    optn: ssd,noatime,compress=zstd,commit=120
    luks: crypt_root
  # Parameters for chroot environment
  host:
    name: scadrial
    user: mistborn
    path: /mnt/debootpath
    tzne: America/Los_Angeles
    # Set any console login parameters for boot-time access via serial (null modem) cable
    # https://tldp.org/HOWTO/Remote-Serial-Console-HOWTO/configure-kernel.html
    # Note: when multiple consoles are listed, although output is sent to all consoles, input is taken from the last listed console
    tty1: y
    stty: ttyS0,115200n8
    # Install cockpit (y/N)
    cpit: y
    # Block nouveau driver
    nblk: y
  # Parameters for networking (netplan) configuration
  # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-consistent_network_device_naming
  # https://ubuntu.com/blog/ubuntu-bionic-netplan
  network:
    # wide-area network
    wan:
      iface: eno1
    # local-area network
    lan:
      iface: enp4s0
      addrs: 10.16.35.1/24
    # wireless access point
    wap:
      iface: wlp2s0
      addrs: 10.16.45.1/24
      # replace passphrase with something unique
      pass: 3fiWk9IoVYJmNm4unYoHjizWPuf8WsLv
      # rename wireless access point as desired
      ssid: Elend Venture